# Generated by Django 5.2.3 on 2025-07-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherhome", "0002_resource_resourceview_delete_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="level",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
