# Generated by Django 5.2.3 on 2025-06-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="roll_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Numéro d'étudiant"
            ),
        ),
    ]
