# Generated by Django 5.2.6 on 2025-09-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_userprofile_roll_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="filiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("informatique", "Informatique"),
                    ("mathematiques", "Mathématiques"),
                    ("physique", "Physique"),
                    ("chimie", "Chimie"),
                    ("biologie", "Biologie"),
                ],
                max_length=20,
                null=True,
                verbose_name="Filière",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="niveau",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L1", "Licence 1"),
                    ("L2", "Licence 2"),
                    ("L3", "Licence 3"),
                    ("M1", "Master 1"),
                    ("M2", "Master 2"),
                ],
                max_length=2,
                null=True,
                verbose_name="Niveau d'études",
            ),
        ),
    ]
