# Generated by Django 5.2.6 on 2025-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_userprofile_filiere_userprofile_niveau"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="matieres_enseignees",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Matières enseignées"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="matricule",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Matricule enseignant",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="filiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez votre filière"),
                    ("informatique", "Informatique"),
                    ("mathematiques", "Mathématiques"),
                    ("physique", "Physique"),
                    ("chimie", "Chimie"),
                    ("biologie", "Biologie"),
                ],
                max_length=20,
                null=True,
                verbose_name="Filière",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="niveau",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Sélectionnez votre niveau"),
                    ("L1", "Licence 1"),
                    ("L2", "Licence 2"),
                    ("L3", "Licence 3"),
                    ("M1", "Master 1"),
                    ("M2", "Master 2"),
                ],
                max_length=2,
                null=True,
                verbose_name="Niveau d'études",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Étudiant"), ("teacher", "Enseignant")],
                max_length=10,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
